### ISSUE TITLE
timezone issue

### ISSUE THREAD

**Issue by killmasta93** [minhng92/odoo-16-docker-compose#7]
Hi
Currently on the message logs of odoo shows the wrong time already changed the user correctly to the time zone but in the logs keep showing the wrong time

![image](https://github.com/minhng92/odoo-16-docker-compose/assets/13953629/06f8064a-6056-490d-9339-77cecd221c48)

![image](https://github.com/minhng92/odoo-16-docker-compose/assets/13953629/06b665ce-2467-4c15-b6a8-396537d12149)

**Comment by minhng92** [comment]
Hi @killmasta93 ,

By default, the time of the message logs is UTC timezone because we haven't configured the timezone inside the Odoo container.

One way you can try, uncomment two lines **/etc/timezone** and **/etc/localtime** in **docker-compose.yml**
https://github.com/minhng92/odoo-16-docker-compose/blob/c28f67b805413b7ebe7c8c4a91c1db38b67e2f83/docker-compose.yml#L29-L30
Then the timezone of Odoo container will be the same with the host. You should re-check the time shown on Odoo to make sure everything works correctly.

Down and up the running containers to take affect the changes on docker-compose.yml:

``` bash
$ cd odoo-16-docker-compose
$ docker-compose down
$ docker-compose up -d
```

**Comment by killmasta93** [comment]
thank you so much that did the trick
